config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :posts

  namespace :admin do
    root to: "home#index"
  end
end

app/models/account.rb
class Account < ApplicationRecord
  include Rodauth::Rails.model
  enum :status, unverified: 1, verified: 2, closed: 3

  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  self.inheritance_column = "_disabled" # free up the "type" column
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account, optional: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :account, optional: true
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  layout "admin"
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController
  def index
  end
end

app/controllers/admin/rodauth_controller.rb
class Admin::RodauthController < Admin::ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_account
    rodauth.rails_account
  end
  helper_method :current_account

  def authenticate
    rodauth.require_account
  end
end

app/controllers/authentication_controller.rb
# Used by lib/authentication/app.rb for rendering views and CSRF protection
class AuthenticationController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = current_account.posts.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = current_account.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_account.posts.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.', status: 303
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_account.posts.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/rodauth_controller.rb
class RodauthController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = nil)
    if title
      @page_title = title
    else
      @page_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom mb-4">
  <div class="container">
    <%= link_to "Rodauth Demo", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-nav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar-nav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", admin_root_path, class: "nav-link #{"active" if controller.is_a?(Admin::HomeController)}" %>
        </li>
      </ul>
    </div>

    <% if rodauth(:admin).logged_in? %>
      <div class="dropdown">
        <button class="btn btn-info dropdown-toggle" data-bs-toggle="dropdown" type="button">
          Account
        </button>
        <div class="dropdown-menu dropdown-menu-end">
          <%= link_to "Change password", rodauth(:admin).change_password_path, class: "dropdown-item" %>
          <%= link_to "Change email", rodauth(:admin).change_login_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Manage MFA", rodauth(:admin).two_factor_manage_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Close account", rodauth(:admin).close_account_path, class: "dropdown-item text-danger" %>
          <%= link_to "Sign out", rodauth(:admin).logout_path, data: { turbo_method: :post }, class: "dropdown-item" %>
        </div>
      </div>
    <% else %>
      <div>
        <%= link_to "Sign in", rodauth(:admin).login_path, class: "btn btn-light" %>
      </div>
    <% end %>
  </div>
</nav>

app/views/admin/home/index.html.erb
<% page_title "Admin" %>

<p>Hello from Admin!</p>

app/views/admin/rodauth/_login_form_footer.html.erb
<% unless rodauth(:admin).login_form_footer_links.empty? %>
  <%== rodauth(:admin).login_form_footer_links_heading %>

  <ul>
    <% if rodauth(:admin).omniauth_providers.include?(:github) %>
      <li>
        <%= button_to "Login via GitHub", rodauth(:admin).omniauth_request_path(:github),
          method: :post, data: { turbo: false }, class: "btn btn-link p-0" %>
      </li>
    <% end %>
    <% rodauth(:admin).login_form_footer_links.sort.each do |_, link, text| %>
      <li><%= link_to text, link %></li>
    <% end %>
  </ul>
<% end %>

app/views/application/_flash.html.erb
<% if notice %>
  <div class="alert alert-success" data-turbo-temporary><%= notice %></div>
<% end %>

<% if alert %>
  <div class="alert alert-danger" data-turbo-temporary><%= alert %></div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark border-bottom mb-4">
  <div class="container">
    <%= link_to "Rodauth Demo", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-nav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar-nav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link #{"active" if controller.is_a?(HomeController)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Posts", posts_path, class: "nav-link #{"active" if controller.is_a?(PostsController)}" %>
        </li>
      </ul>
    </div>

    <% if rodauth.logged_in? %>
      <div class="dropdown">
        <button class="btn btn-info dropdown-toggle" data-bs-toggle="dropdown" type="button">
          <%= current_account.profile.name %> (<%= rodauth.authenticated_by.join(", ") %>)
        </button>
        <div class="dropdown-menu dropdown-menu-end">
          <%= link_to "Change password", rodauth.change_password_path, class: "dropdown-item" %>
          <%= link_to "Change email", rodauth.change_login_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Manage MFA", rodauth.two_factor_manage_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Close account", rodauth.close_account_path, class: "dropdown-item text-danger" %>
          <%= link_to "Sign out", rodauth.logout_path, data: { turbo_method: :post }, class: "dropdown-item" %>
        </div>
      </div>
    <% else %>
      <div>
        <%= link_to "Sign in", rodauth.login_path, class: "btn btn-outline-primary" %>
        <%= link_to "Sign up", rodauth.create_account_path, class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</nav>

app/views/authentication/register.html.erb
<%= form_tag auth.register_path, action: "post" do %>
  <div class="form-group">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email], class: "form-control" %>
    <small class="form-text text-danger"><%= auth.field_error(:email) %></small>
  </div>
  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= label_tag :password %>
        <%= password_field_tag :password, params[:password], class: "form-control" %>
        <small class="form-text text-danger"><%= auth.field_error(:password) %></small>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= label_tag :confirm_password %>
        <%= password_field_tag :confirm_password, params[:confirm_password], class: "form-control" %>
        <small class="form-text text-danger"><%= auth.field_error(:confirm_password) %></small>
      </div>
    </div>
  </div>
  <%= submit_tag "Create account", class: "btn btn-primary" %>
<% end %>

app/views/home/index.html.erb
<% page_title "Home" %>

<div class="py-4 px-5 bg-dark border">
  <h1 class="display-4 mb-4">Rodauth Rails Demo</h1>
  <p class="lead">This application demonstrates a possible integration of <%= link_to "Rodauth", "http://rodauth.jeremyevans.net", target: "_blank" %> into a Rails application, using the <%= link_to "rodauth-rails", "https://github.com/janko/rodauth-rails", target: "_blank" %> gem.</p>
  <p class="lead">You can find the source code at <%= link_to "github.com/janko/rodauth-demo-rails", "https://github.com/janko/rodauth-demo-rails", target: "_blank" %>.</p>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "#{@page_title} • Rodauth Demo" %></title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script type="module" src="https://unpkg.com/@hotwired/turbo"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body class="bg-light">
    <%= render "navbar" %>

    <div class="container">
      <%= render "flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
  <head>
    <title><%= "#{@page_title} • Rodauth Demo" %></title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "navbar" %>

    <div class="container">
      <%= render "flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: "form-label" %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% page_title "Editing Post" %>

<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, class: "btn btn-secondary" %>
<%= link_to 'Back', posts_path, class: "btn btn-link" %>

app/views/posts/index.html.erb
<% page_title "Posts" %>

<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td>
          <%= link_to 'Show', post, class: "btn btn-secondary" %>
          <%= link_to 'Edit', edit_post_path(post), class: "btn btn-warning" %>
          <%= link_to 'Destroy', post, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, class: "btn btn-success" %>

app/views/posts/new.html.erb
<% page_title "New Post" %>

<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% page_title @post.title %>

<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning" %>
<%= link_to 'Back', posts_path, class: "btn btn-link" %>

app/views/rodauth/_email_auth_request_form.html.erb
<%= form_with url: rodauth.email_auth_request_path, method: :post do |form| %>
  <%= form.hidden_field rodauth.login_param, value: params[rodauth.login_param] %>

  <div class="mb-3">
    <%= form.submit rodauth.email_auth_request_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/_login_form.html.erb
<%= form_with url: rodauth.login_path, method: :post, data: { turbo: false } do |form| %>
  <% if rodauth.skip_login_field_on_login? %>
    <div class="mb-3">
      <%= form.label "login", rodauth.login_label, class: "form-label" %>
      <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", readonly: true, class: "form-control-plaintext" %>
    </div>
  <% else %>
    <div class="mb-3">
      <%= form.label "login", rodauth.login_label, class: "form-label" %>
      <%= form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", autocomplete: rodauth.login_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.login_param)}", aria: ({ invalid: true, describedby: "login_error_message" } if rodauth.field_error(rodauth.login_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.login_param), class: "invalid-feedback", id: "login_error_message") if rodauth.field_error(rodauth.login_param) %>
    </div>
  <% end %>

  <% unless rodauth.skip_password_field_on_login? %>
    <div class="mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.submit rodauth.login_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/close_account.html.erb
<%= form_with url: rodauth.close_account_path, method: :post do |form| %>
  <% if rodauth.close_account_requires_password? %>
    <div class="mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.submit rodauth.close_account_button, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/rodauth/email_auth.html.erb
<%= form_with url: rodauth.email_auth_path, method: :post, data: { controller: "submit" }, class: "d-none" do |form| %>
  <div class="mb-3">
    <%= form.submit rodauth.login_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/logout.html.erb
<%= form_with url: rodauth.logout_path, method: :post do |form| %>
  <% if rodauth.features.include?(:active_sessions) %>
    <div class="mb-3">
      <div class="form-check">
        <%= form.check_box rodauth.global_logout_param, id: "global-logout", class: "form-check-input", include_hidden: false %>
        <%= form.label "global-logout", rodauth.global_logout_label, class: "form-check-label" %>
      </div>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.submit rodauth.logout_button, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/rodauth/otp_disable.html.erb
<%= form_with url: rodauth.otp_disable_path, method: :post do |form| %>
  <% if rodauth.two_factor_modifications_require_password? %>
    <div class="mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.submit rodauth.otp_disable_button, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/rodauth/recovery_auth.html.erb
<%= form_with url: rodauth.recovery_auth_path, method: :post do |form| %>
  <div class="mb-3">
    <%= form.label "recovery-code", rodauth.recovery_codes_label, class: "form-label" %>
    <%= form.text_field rodauth.recovery_codes_param, value: "", id: "recovery-code", autocomplete: "off", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.recovery_codes_param)}", aria: ({ invalid: true, describedby: "recovery-code_error_message" } if rodauth.field_error(rodauth.recovery_codes_param)) %>
    <%= content_tag(:span, rodauth.field_error(rodauth.recovery_codes_param), class: "invalid-feedback", id: "recovery-code_error_message") if rodauth.field_error(rodauth.recovery_codes_param) %>
  </div>

  <div class="mb-3">
    <%= form.submit rodauth.recovery_auth_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/recovery_codes.html.erb
<%= form_with url: rodauth.recovery_codes_path, method: :post, data: { turbo: false } do |form| %>
  <% if rodauth.two_factor_modifications_require_password? %>
    <div class="mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.submit rodauth.recovery_codes_button || rodauth.view_recovery_codes_button, name: (rodauth.add_recovery_codes_param if rodauth.recovery_codes_button), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/sms_disable.html.erb
<%= form_with url: rodauth.sms_disable_path, method: :post do |form| %>
  <% if rodauth.two_factor_modifications_require_password? %>
    <div class="mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.submit rodauth.sms_disable_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/sms_setup.html.erb
<%= form_with url: rodauth.sms_setup_path, method: :post do |form| %>
  <% if rodauth.two_factor_modifications_require_password? %>
    <div class="mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label "sms-phone", rodauth.sms_phone_label, class: "form-label" %>
    <div class="row">
      <div class="col-sm-3">
        <%= form.telephone_field rodauth.sms_phone_param, value: "", id: "sms-phone", autocomplete: "tel", required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.sms_phone_param)}", aria: ({ invalid: true, describedby: "sms-phone_error_message" } if rodauth.field_error(rodauth.sms_phone_param)) %>
        <%= content_tag(:span, rodauth.field_error(rodauth.sms_phone_param), class: "invalid-feedback", id: "sms-phone_error_message") if rodauth.field_error(rodauth.sms_phone_param) %>
      </div>
    </div>
  </div>

  <div class="mb-3">
    <%= form.submit rodauth.sms_setup_button, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rodauth/two_factor_auth.html.erb
<ul>
  <% rodauth.two_factor_auth_links.sort.each do |_, link, text| %>
    <li><%= link_to text, link %></li>
  <% end %>
</ul>

app/views/rodauth/two_factor_manage.html.erb
<% if rodauth.two_factor_setup_links.any? %>
  <%== rodauth.two_factor_setup_heading %>

  <ul>
    <% rodauth.two_factor_setup_links.sort.each do |_, link, text| %>
      <li><%= link_to text, link %></li>
    <% end %>
  </ul>
<% end %>

<% if current_account.webauthn_keys.any? %>
  <h2>WebAuthn credentials</h2>
  <ul>
    <% current_account.webauthn_keys.each do |webauthn_key| %>
      <li><%= webauthn_key.nickname %></li>
    <% end %>
  </ul>
<% end %>

<% if rodauth.two_factor_remove_links.any? %>
  <%== rodauth.two_factor_remove_heading %>

  <ul>
    <% rodauth.two_factor_remove_links.sort.each do |_, link, text| %>
      <li><%= link_to text, link %></li>
    <% end %>
    <% if rodauth.two_factor_remove_links.length > 1 %>
      <li><%= link_to rodauth.two_factor_disable_link_text, rodauth.two_factor_disable_path %></li>
    <% end %>
  </ul>
<% end %>

app/views/rodauth/webauthn_auth.html.erb
<% cred = rodauth.webauthn_credential_options_for_get %>

<%= form_with url: rodauth.webauthn_auth_form_path, method: :post, data: { controller: "webauthn", webauthn_data_value: cred.as_json.to_json, turbo: false } do |form| %>
  <%= form.hidden_field rodauth.webauthn_auth_param, data: { webauthn_target: "result" } %>
  <%= form.hidden_field rodauth.webauthn_auth_challenge_param, value: cred.challenge %>
  <%= form.hidden_field rodauth.webauthn_auth_challenge_hmac_param, value: rodauth.compute_hmac(cred.challenge) %>

  <% if request.path == rodauth.login_path && rodauth.valid_login_entered? %>
    <%= form.hidden_field rodauth.login_param, value: params[rodauth.login_param] %>
  <% end %>

  <div class="mb-3">
    <%= form.submit rodauth.webauthn_auth_button, class: "btn btn-primary", data: { action: "webauthn#auth:prevent" } %>
  </div>
<% end %>

app/views/rodauth/webauthn_setup.html.erb
<% cred = rodauth.new_webauthn_credential %>

<%= form_with url: request.path, method: :post, data: { controller: "webauthn", webauthn_data_value: cred.as_json.to_json, turbo: false } do |form| %>
  <%= form.hidden_field rodauth.webauthn_setup_param, data: { webauthn_target: "result" } %>
  <%= form.hidden_field rodauth.webauthn_setup_challenge_param, value: cred.challenge %>
  <%= form.hidden_field rodauth.webauthn_setup_challenge_hmac_param, value: rodauth.compute_hmac(cred.challenge) %>

  <div class="mb-3">
    <%= form.label :nickname, "Nickname", class: "form-label" %>
    <%= form.text_field :nickname, value: params[:nickname], class: "form-control #{"is-invalid" if rodauth.field_error("nickname")}", aria: ({ invalid: true, describedby: "nickname_error_message" } if rodauth.field_error("nickname")) %>
    <%= content_tag(:span, rodauth.field_error("nickname"), class: "invalid-feedback", id: "nickname_error_message") if rodauth.field_error("nickname") %>
  </div>

  <% if rodauth.two_factor_modifications_require_password? %>
    <div class="mb-3">
      <%= form.label "password", rodauth.password_label, class: "form-label" %>
      <%= form.password_field rodauth.password_param, value: "", id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true, class: "form-control #{"is-invalid" if rodauth.field_error(rodauth.password_param)}", aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param)) %>
      <%= content_tag(:span, rodauth.field_error(rodauth.password_param), class: "invalid-feedback", id: "password_error_message") if rodauth.field_error(rodauth.password_param) %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.submit rodauth.webauthn_setup_button, class: "btn btn-primary", data: { action: "webauthn#setup:prevent" } %>
  </div>
<% end %>